updated dashboards.js
chutten/telemetry-dashboard pull request #1
Opened 2017-04-10 23:33 UTC by hemant1612

@chutten 
Added document.execCommand('copy') in the response handler .
I think i am right here : )

some background: 

- [https://jsfiddle.net/homz0zv0/1/](https://jsfiddle.net/homz0zv0/1/)

- [https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)

2017-04-11 14:10 UTC, chutten commented
First appearances look good, but there are a couple things you can do to make it better. First and foremost, writing a good commit message is necessary. A good format we follow is
```
bug <###> - Made foo do bar

Foo previously didn't do bar because baz took care of it.
```

Essentially: bug number in the subject line, a quick summary of what the commit did ("updated dashboard.js" is something we can tell from git, you don't need to tell us that. Try something like "Copy the shortened link"), and then any background information or reasons why you did it one way instead of another (For instance, I'm not clear on why you didn't just call document.execCommand("copy"); on its own line instead of using the jQuery wrapper. Also, what's the browser support like for execCommand?)

And, if you want to make things _really_ easy for me, you can push this to your gh-pages branch and have github host it for you so I can review a live preview of the code :)

2017-04-11 15:35 UTC, hemant1612 commented
Yea I will do this :) & thanks for review.

2017-04-11 20:41 UTC, chutten requested changes
Please squash these two commits together into one and address the other comment. 

The commit message is much better. I would recommend thinking about good commit message bodies as answering the question "Why?" instead of the question "What?". In my experience reasons tend to be more useful when looking through commit history, and "What?" is usually easy to figure out by looking at the patch contents and the commit message subject line.

Not something you should feel you must do here, but a good habit to develop.

2017-04-11 20:41 UTC, chutten commented on src/dashboards.js
> +               document.execCommand('copy');
Bring the indentation of this line back to the correct level, please.

2017-04-11 21:03 UTC, hemant1612 commented on src/dashboards.js
> +               document.execCommand('copy');
Well I am learning best of open source practices. :)

2017-04-12 10:14 UTC, hemant1612 commented
I have hosted source code here: https://github.com/hemant1612/hemant1612.github.io
However  [https://hemant1612.github.io/new-pipeline/dist.html](https://hemant1612.github.io/new-pipeline/dist.html) is not copying the generated url.
I think its due to a console error.
And `document.execCommand('copy')` needs to be updated in https://github.com/hemant1612/hemant1612.github.io/blob/master/new-pipeline/src/dashboards.js#L170.
I added `alert()`  just for debugging purposes.
Trying to simulate the process [here](https://jsfiddle.net/rgc6kj3g/1/) works fine.

2017-04-12 16:34 UTC, chutten commented
Ah, the good ol' `document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.`

This is probably because the `execCommand` call is inside the xhr's handler, not the button's. If you force the XHR to be synchronous and pull the `execCommand` line out into the button's handler instead, does it work?

2017-04-12 20:01 UTC, hemant1612 commented
I strongly agree with you here.However still it is not working.
https://github.com/hemant1612/hemant1612.github.io/blob/master/new-pipeline/src/dashboards.js#L170

2017-04-12 20:06 UTC, chutten commented
Slapping a breakpoint on the `execCommand` is showing that it is being called before the selection is happening. So it is working! But there isn't anything yet selected for it to copy.

Make sure the XHR is completing synchronously, I guess? And if it is, make sure the input's value is being set at the right time and focus is being processed correctly.

2017-04-13 09:08 UTC, hemant1612 commented
Finally gotta it work.

The way I tried to implement it earlier was not working because 

- Copy and cut commands triggered through a scripting API will only affect the contents of the real clipboard if the event is dispatched from an event that is trusted and triggered by the user, or if the implementation is configured to allow this. [W3 SPECS](https://www.w3.org/TR/clipboard-apis/#integration-with-rich-text-editing-apis)

Here a `$(window).blur() or $(document).click() event` can save the life.
Or to populate the input by the time user has clicked which I have done [here](https://github.com/hemant1612/hemant1612.github.io/blob/master/new-pipeline/src/dashboards.js#L130).

2017-04-13 16:16 UTC, chutten requested changes
I see what the problem is. `dataType: "jsonp"`

There is no such thing as a synchronous jsonp request.

So either we get the short urls every time the url changes and call copy when the link button is clicked (which is not dissimilar to what you have here, just with more calls to `getIt()`)

Or we go back to the person asking for this feature and say "Sorry, can't do it"

Personally, I'm aiming for the second. Unless there _is_ a synchronous way to shorten a url using the bitly API.

2017-04-13 16:16 UTC, chutten commented on new-pipeline/src/dashboards.js
> +getIt();
This means you're getting the short url on the pageload, not after the user has made their selection (which changes the url parameters).

2017-04-13 16:16 UTC, chutten commented on new-pipeline/src/dashboards.js
> +   $(".permalink-control")
The indentation here is wrong

2017-04-13 16:16 UTC, chutten commented on src/dashboards.js
> +            document.execCommand('copy');
Don't bother with src/dashboards.js. It is deprecated.

2017-04-13 16:16 UTC, chutten commented on new-pipeline/src/dashboards.js
> +   $(".permalink-control")
The indentation here is wrong.

2017-04-14 14:23 UTC, hemant1612 commented
I think we can't make API responses synchronous at least in any way that won't freeze the browser because network connections are fundamentally asynchronous . I have asked  bitly developers  about that .Hope they reply soon..  :)
What about the first option we have !

2017-04-18 14:15 UTC, chutten commented
I think a normal XHR using the modern [v3 bit.ly API](http://dev.bitly.com/links.html#v3_shorten) can be made synchronous as it serves its JSON response in the response body. I'm okay if this is a source of lag, as it is in response to a user interaction (so we're allowed to be a little slower) and bit.ly's service tends to be pretty rapid.

2017-04-20 02:25 UTC, hemant1612 commented on src/dashboards.js
> +            document.execCommand('copy');
Please review the changes :) and it is working fine.

2017-04-20 13:52 UTC, chutten commented
The system works!

Can you squash all these commits into a single one with an excellent commit message? Then we can get this in and live on telemetry.mozilla.org

2017-04-20 13:53 UTC, hemant1612 commented
sure :).

2017-04-20 13:53 UTC, chutten commented
Oh! And in all this I never noticed that you submitted this pull request against chutten/telemetry-dashboard instead of mozilla/telemetry-dashboard. Could you move it over there?

2017-04-20 13:55 UTC, hemant1612 commented
LGTM

2020-06-08 16:00 UTC, closed without merging